@echo off
:: clean_exporter_artifacts.bat
:: Removes all artifacts generated by the Minecraft exporter pipeline.

cd /d "%~dp0"

echo ============================================================
echo Cleaning exporter artifacts...

set "OUTPUT_DIR=export\minecraft_world"

if exist "%OUTPUT_DIR%" (
    echo Removing output directory: %OUTPUT_DIR%
    rmdir /s /q "%OUTPUT_DIR%"
) else (
    echo No output directory found at %OUTPUT_DIR%
)

set "ROAD_META=export\road_metadata.json"
if exist "%ROAD_META%" (
    echo Removing file: %ROAD_META%
    del /f /q "%ROAD_META%"
)

set "TERRAIN_CLASS=export\terrain_classification.json"
if exist "%TERRAIN_CLASS%" (
    echo Removing file: %TERRAIN_CLASS%
    del /f /q "%TERRAIN_CLASS%"
)

set "HEIGHT_CACHE=data\terrain_height_cache.json"
if exist "%HEIGHT_CACHE%" (
    echo Removing file: %HEIGHT_CACHE%
    del /f /q "%HEIGHT_CACHE%"
)

echo Clean complete!
echo ============================================================
