#!/usr/bin/env bash

# clean_exporter_artifacts.sh
# Removes all artifacts generated by the Minecraft exporter pipeline.

set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")"

echo "============================================================"
# Clean default exporter outputs
OUTPUT_DIR="export/minecraft_world"

echo "Cleaning exporter artifacts..."

# 1. Remove generated Minecraft world saves and caches
if [ -d "$OUTPUT_DIR" ]; then
    echo "Removing output directory: $OUTPUT_DIR"
    rm -rf "$OUTPUT_DIR/TecateWorld"
else
    echo "No output directory found at $OUTPUT_DIR"
fi

# 2. Remove generated metadata and classification caches
METADATA_FILES=(
    "export/road_metadata.json"
    "export/terrain_classification.json"
    "export/minecraft_world/terrain_height_cache.json"
    "export/minecraft_world/TecateWorld/tecate_metadata.json"
)

for file in "${METADATA_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "Removing file: $file"
        rm -f "$file"
    fi
done

echo "Clean complete!"
echo "============================================================"
